### ISSUE TITLE
Проблема со StartStopTest на Windows

### ISSUE THREAD

**Issue by wndrws** [polis-mail-ru/2018-highload-kv#34]
Если я правильно помню, об этом несколько раз говорилось на занятиях: на винде большой таймаут на ожидание ответа от сокета, и когда мы проверяем, что нам не отвечают и хотим получить исключение `PoolException` из one-nio, то ждать придётся очень долго, и поэтому тесты `StartStopTest.create()` и `StartStopTest.stop()` не проходят - клиент не получает ответа от системы за те 2 секунды, что мы ему даём, и не может кинуть ожидаемое исключение.

У меня есть решение этой проблемы - https://github.com/polis-mail-ru/2018-highload-kv/pull/19/commits/6451195079fa8a06d582e4f4c285f233ce91e47a , но я не знаю, как мне сделать пулл-реквест только с этим коммитом, без всех остальных изменений из моего форка.

**Comment by wndrws** [comment]
@incubos

**Comment by incubos** [comment]
Здорово, что удалось запедалить workaround.
Предлагаю отвести в Вашем fork'е отдельную ветку от оригинальной головы upstream `master`, закоммитить фикс и прислать pull request из ветки в `master`.

**Comment by wndrws** [comment]
Спасибо, сделал как Вы предложили - см. pull request #40

**Comment by incubos** [comment]
Вмёрджил. Спасибо!
